# Generated by Django 4.1.5 on 2023-01-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angajati', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angajati',
            name='varsta',
        ),
    ]
