# Generated by Django 4.1.5 on 2023-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angajati', '0002_remove_angajati_varsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='angajati',
            name='varsta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
